### ISSUE TITLE
Not working in anki 2.1.10

### ISSUE THREAD

**Issue by orangelover12** [Rytisgit/Anki-StylusDraw#13]
Hello! 
I'm sorry for frequently writing about issues. :')
My issue is that ANKI 2.1.10 version came out today and this addon does not work.
I would really appreciate it if you could update it.
Have a good day!

**Comment by Rytisgit** [comment]
It only doesn't work on the qt6 version. You can use qt5.

**Comment by orangelover12** [comment]
Oh, I see. Thank you for answer! Have a great day, Rytisgit !

**Comment by Rytisgit** [comment]
It was a few small changes, good thing that this addon is not using the anki interface in a complicated way. Should be working now.

**Comment by orangelover12** [comment]
Thank you so much! Now it works perfectly on 23.10 QT6 as well. Thank you for taking the time to fix it. Hope you have a wonderful day!

**Comment by Aveeno1432** [comment]
Does this currently work on 23.10 QT6?
I updated to anki 23.10 today and the following bug occurs:
Could you tell me what the problem is?

Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-05 16:19:06

When loading AnkiDraw - Draw and write using mouse and stylus with pressure support:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\dj108\AppData\Roaming\Anki2\addons21\1868980340\__init__.py", line 36, in <module>
    from PyQt5.QtWidgets import QAction, QMenu, QColorDialog, QMessageBox, QInputDialog, QApplication, QMainWindow, QLabel,\
ModuleNotFoundError: No module named 'PyQt5'

**Comment by Rytisgit** [comment]
Hi there @Aveeno1432,

thanks for reporting, looks like this was an issue due to setting the supported versions for anki. I was able to fix it by reuploading again, and now it is triggering the update for me every time. So you should be able to just restart or check for updates and it should find the new version as well,
